version: "3.9"

services:
  minecraft:
    image: "marctv/minecraft-papermc-server:1.18"
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "4G"
      ENABLE_RCON: "true"
      EULA: "TRUE"
    volumes:
      - type: bind
        source: /c/minecraft
        target: /data
    restart: unless-stopped    
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
    